// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmq3RqktmdkgIcNsyjny9MCIU7fFXJjxk',
    appId: '1:893349040607:web:cc7ca5279c917d36bf346a',
    messagingSenderId: '893349040607',
    projectId: 'myshoppingapp-bbb18',
    authDomain: 'myshoppingapp-bbb18.firebaseapp.com',
    storageBucket: 'myshoppingapp-bbb18.appspot.com',
    measurementId: 'G-WWHTK3RPZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeFA7o38ClQzAr09htTGH24PiMDvrC9LA',
    appId: '1:893349040607:android:4654fde27f6c91fdbf346a',
    messagingSenderId: '893349040607',
    projectId: 'myshoppingapp-bbb18',
    storageBucket: 'myshoppingapp-bbb18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_dl-WXn0uOY-6XjwN-zgnrswmt44tN7Y',
    appId: '1:893349040607:ios:834fc8abf43b8e16bf346a',
    messagingSenderId: '893349040607',
    projectId: 'myshoppingapp-bbb18',
    storageBucket: 'myshoppingapp-bbb18.appspot.com',
    iosClientId: '893349040607-kjioq2pm5b1juea5hods65fo5ffqrsvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart',
  );
}
